/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'content' : string,
  'role' : T__1,
  'timestamp' : Time,
}
export interface GameAnalytics {
  'title' : string,
  'gameId' : string,
  'clickCount' : bigint,
  'category' : T,
}
export type Page = { 'about' : null } |
  { 'resources' : null } |
  { 'home' : null } |
  { 'games' : null };
export interface Resource {
  'id' : string,
  'url' : string,
  'title' : string,
  'subject' : T__2,
  'description' : string,
}
export type T = { 'strategy' : null } |
  { 'puzzles' : null } |
  { 'arcade' : null };
export type T__1 = { 'user' : null } |
  { 'assistant' : null };
export type T__2 = { 'wellbeing' : null } |
  { 'math' : null } |
  { 'generalKnowledge' : null } |
  { 'english' : null } |
  { 'science' : null };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'createSession' : ActorMethod<[string], undefined>,
  'getAllResources' : ActorMethod<[], Array<Resource>>,
  'getGameAnalytics' : ActorMethod<[], Array<GameAnalytics>>,
  'getPageVisits' : ActorMethod<[], Array<[string, bigint]>>,
  'getResourcesBySubject' : ActorMethod<[T__2], Array<Resource>>,
  'getSessionMessages' : ActorMethod<[string], Array<ChatMessage>>,
  'getTopGames' : ActorMethod<[bigint], Array<GameAnalytics>>,
  'getTotalGameClicks' : ActorMethod<[], bigint>,
  'getTotalSiteVisits' : ActorMethod<[], bigint>,
  'recordGameClick' : ActorMethod<[string, string, T], undefined>,
  'recordPageVisit' : ActorMethod<[Page], undefined>,
  'sendMessageToAI' : ActorMethod<[string, string], string>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];