/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const T__2 = IDL.Variant({
  'wellbeing' : IDL.Null,
  'math' : IDL.Null,
  'generalKnowledge' : IDL.Null,
  'english' : IDL.Null,
  'science' : IDL.Null,
});
export const Resource = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'subject' : T__2,
  'description' : IDL.Text,
});
export const T = IDL.Variant({
  'strategy' : IDL.Null,
  'puzzles' : IDL.Null,
  'arcade' : IDL.Null,
});
export const GameAnalytics = IDL.Record({
  'title' : IDL.Text,
  'gameId' : IDL.Text,
  'clickCount' : IDL.Nat,
  'category' : T,
});
export const T__1 = IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null });
export const Time = IDL.Int;
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'role' : T__1,
  'timestamp' : Time,
});
export const Page = IDL.Variant({
  'about' : IDL.Null,
  'resources' : IDL.Null,
  'home' : IDL.Null,
  'games' : IDL.Null,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'createSession' : IDL.Func([IDL.Text], [], []),
  'getAllResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
  'getGameAnalytics' : IDL.Func([], [IDL.Vec(GameAnalytics)], ['query']),
  'getPageVisits' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getResourcesBySubject' : IDL.Func([T__2], [IDL.Vec(Resource)], ['query']),
  'getSessionMessages' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ChatMessage)],
      ['query'],
    ),
  'getTopGames' : IDL.Func([IDL.Nat], [IDL.Vec(GameAnalytics)], ['query']),
  'getTotalGameClicks' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalSiteVisits' : IDL.Func([], [IDL.Nat], ['query']),
  'recordGameClick' : IDL.Func([IDL.Text, IDL.Text, T], [], []),
  'recordPageVisit' : IDL.Func([Page], [], []),
  'sendMessageToAI' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const T__2 = IDL.Variant({
    'wellbeing' : IDL.Null,
    'math' : IDL.Null,
    'generalKnowledge' : IDL.Null,
    'english' : IDL.Null,
    'science' : IDL.Null,
  });
  const Resource = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'subject' : T__2,
    'description' : IDL.Text,
  });
  const T = IDL.Variant({
    'strategy' : IDL.Null,
    'puzzles' : IDL.Null,
    'arcade' : IDL.Null,
  });
  const GameAnalytics = IDL.Record({
    'title' : IDL.Text,
    'gameId' : IDL.Text,
    'clickCount' : IDL.Nat,
    'category' : T,
  });
  const T__1 = IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null });
  const Time = IDL.Int;
  const ChatMessage = IDL.Record({
    'content' : IDL.Text,
    'role' : T__1,
    'timestamp' : Time,
  });
  const Page = IDL.Variant({
    'about' : IDL.Null,
    'resources' : IDL.Null,
    'home' : IDL.Null,
    'games' : IDL.Null,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'createSession' : IDL.Func([IDL.Text], [], []),
    'getAllResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
    'getGameAnalytics' : IDL.Func([], [IDL.Vec(GameAnalytics)], ['query']),
    'getPageVisits' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getResourcesBySubject' : IDL.Func([T__2], [IDL.Vec(Resource)], ['query']),
    'getSessionMessages' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getTopGames' : IDL.Func([IDL.Nat], [IDL.Vec(GameAnalytics)], ['query']),
    'getTotalGameClicks' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalSiteVisits' : IDL.Func([], [IDL.Nat], ['query']),
    'recordGameClick' : IDL.Func([IDL.Text, IDL.Text, T], [], []),
    'recordPageVisit' : IDL.Func([Page], [], []),
    'sendMessageToAI' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };