/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Resource {
    id: string;
    url: string;
    title: string;
    subject: T__2;
    description: string;
}
export interface GameAnalytics {
    title: string;
    gameId: string;
    clickCount: bigint;
    category: T;
}
export interface ChatMessage {
    content: string;
    role: T__1;
    timestamp: Time;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export enum Page {
    about = "about",
    resources = "resources",
    home = "home",
    games = "games"
}
export enum T {
    strategy = "strategy",
    puzzles = "puzzles",
    arcade = "arcade"
}
export enum T__1 {
    user = "user",
    assistant = "assistant"
}
export enum T__2 {
    wellbeing = "wellbeing",
    math = "math",
    generalKnowledge = "generalKnowledge",
    english = "english",
    science = "science"
}
export interface backendInterface {
    createSession(sessionId: string): Promise<void>;
    getAllResources(): Promise<Array<Resource>>;
    getGameAnalytics(): Promise<Array<GameAnalytics>>;
    getPageVisits(): Promise<Array<[string, bigint]>>;
    getResourcesBySubject(subject: T__2): Promise<Array<Resource>>;
    getSessionMessages(sessionId: string): Promise<Array<ChatMessage>>;
    getTopGames(limit: bigint): Promise<Array<GameAnalytics>>;
    getTotalGameClicks(): Promise<bigint>;
    getTotalSiteVisits(): Promise<bigint>;
    recordGameClick(gameId: string, title: string, category: T): Promise<void>;
    recordPageVisit(page: Page): Promise<void>;
    sendMessageToAI(sessionId: string, message: string): Promise<string>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { ChatMessage as _ChatMessage, GameAnalytics as _GameAnalytics, Page as _Page, Resource as _Resource, T as _T, T__1 as _T__1, T__2 as _T__2, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createSession(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSession(arg0);
            return result;
        }
    }
    async getAllResources(): Promise<Array<Resource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllResources();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllResources();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGameAnalytics(): Promise<Array<GameAnalytics>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGameAnalytics();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGameAnalytics();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPageVisits(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPageVisits();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPageVisits();
            return result;
        }
    }
    async getResourcesBySubject(arg0: T__2): Promise<Array<Resource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResourcesBySubject(to_candid_T__2_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResourcesBySubject(to_candid_T__2_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSessionMessages(arg0: string): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionMessages(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionMessages(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopGames(arg0: bigint): Promise<Array<GameAnalytics>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopGames(arg0);
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopGames(arg0);
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalGameClicks(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalGameClicks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalGameClicks();
            return result;
        }
    }
    async getTotalSiteVisits(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalSiteVisits();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalSiteVisits();
            return result;
        }
    }
    async recordGameClick(arg0: string, arg1: string, arg2: T): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordGameClick(arg0, arg1, to_candid_T_n18(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordGameClick(arg0, arg1, to_candid_T_n18(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async recordPageVisit(arg0: Page): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPageVisit(to_candid_Page_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPageVisit(to_candid_Page_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendMessageToAI(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessageToAI(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessageToAI(arg0, arg1);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_ChatMessage_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatMessage): ChatMessage {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_GameAnalytics_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameAnalytics): GameAnalytics {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Resource_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Resource): Resource {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_T__1_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T__1): T__1 {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_T__2_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T__2): T__2 {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_T_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T): T {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: string;
    role: _T__1;
    timestamp: _Time;
}): {
    content: string;
    role: T__1;
    timestamp: Time;
} {
    return {
        content: value.content,
        role: from_candid_T__1_n16(_uploadFile, _downloadFile, value.role),
        timestamp: value.timestamp
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    url: string;
    title: string;
    subject: _T__2;
    description: string;
}): {
    id: string;
    url: string;
    title: string;
    subject: T__2;
    description: string;
} {
    return {
        id: value.id,
        url: value.url,
        title: value.title,
        subject: from_candid_T__2_n4(_uploadFile, _downloadFile, value.subject),
        description: value.description
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    gameId: string;
    clickCount: bigint;
    category: _T;
}): {
    title: string;
    gameId: string;
    clickCount: bigint;
    category: T;
} {
    return {
        title: value.title,
        gameId: value.gameId,
        clickCount: value.clickCount,
        category: from_candid_T_n9(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    strategy: null;
} | {
    puzzles: null;
} | {
    arcade: null;
}): T {
    return "strategy" in value ? T.strategy : "puzzles" in value ? T.puzzles : "arcade" in value ? T.arcade : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: null;
} | {
    assistant: null;
}): T__1 {
    return "user" in value ? T__1.user : "assistant" in value ? T__1.assistant : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    wellbeing: null;
} | {
    math: null;
} | {
    generalKnowledge: null;
} | {
    english: null;
} | {
    science: null;
}): T__2 {
    return "wellbeing" in value ? T__2.wellbeing : "math" in value ? T__2.math : "generalKnowledge" in value ? T__2.generalKnowledge : "english" in value ? T__2.english : "science" in value ? T__2.science : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Resource>): Array<Resource> {
    return value.map((x)=>from_candid_Resource_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChatMessage>): Array<ChatMessage> {
    return value.map((x)=>from_candid_ChatMessage_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GameAnalytics>): Array<GameAnalytics> {
    return value.map((x)=>from_candid_GameAnalytics_n7(_uploadFile, _downloadFile, x));
}
function to_candid_Page_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Page): _Page {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_T__2_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: T__2): _T__2 {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_T_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: T): _T {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: T__2): {
    wellbeing: null;
} | {
    math: null;
} | {
    generalKnowledge: null;
} | {
    english: null;
} | {
    science: null;
} {
    return value == T__2.wellbeing ? {
        wellbeing: null
    } : value == T__2.math ? {
        math: null
    } : value == T__2.generalKnowledge ? {
        generalKnowledge: null
    } : value == T__2.english ? {
        english: null
    } : value == T__2.science ? {
        science: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: T): {
    strategy: null;
} | {
    puzzles: null;
} | {
    arcade: null;
} {
    return value == T.strategy ? {
        strategy: null
    } : value == T.puzzles ? {
        puzzles: null
    } : value == T.arcade ? {
        arcade: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Page): {
    about: null;
} | {
    resources: null;
} | {
    home: null;
} | {
    games: null;
} {
    return value == Page.about ? {
        about: null
    } : value == Page.resources ? {
        resources: null
    } : value == Page.home ? {
        home: null
    } : value == Page.games ? {
        games: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
